### ISSUE TITLE
Preprocessing for experiments on Epic-kitchen

### ISSUE THREAD

**Issue by lyttonhao** [noureldien/videograph#2]
Thanks a lot for sharing the nice codes!

I just want to run the `main.py` to see the experiments on Epic-Kitchen, but currently some features files under `EPIC-Kitchens/features` are missing. Could you provide these features for downloading? Or helping to point out how to generate them? Thanks a lot!

**Comment by noureldien** [comment]
Hi Yanghao,

Thanks for asking. Please extract the features using this function.
https://github.com/noureldien/videograph/blob/master/datasets/epic_kitchens.py#L679

You will need I3D model. I used this one:
https://github.com/dlpbc/keras-kinetics-i3d/releases
rgb_inception_i3d_imagenet_and_kinetics_tf_dim_ordering_tf_kernels.h5

**Comment by na-hri** [comment]
Hi Noureldien,

Firstly, thanks for sharing the code!

It seems that feature extraction process for Epic-Kitchen requires some files which need to be generated/arranged. Moreover, `i3d_keras_epic_kitchens` definition seems to be missing from your feature extraction function 
https://github.com/noureldien/videograph/blob/master/datasets/epic_kitchens.py#L709
Could you please clearly list out the steps/files required for pre-processing so that it's clear for everyone? Thanks!

Also, any plans on releasing the pre-processing scripts for other datasets (Breakfast and Charades)?

**Comment by noureldien** [comment]
Hi, thanks for asking.
1. i3d_keras_epic_kitchens is the same as https://github.com/dlpbc/keras-kinetics-i3d/releases
2. Please, what files are missing? All annotation files can be generated using functions in the python file epic_kitchens. Please point me out if something is missing.

**Comment by na-hri** [comment]
Thanks for the prompt response!

1) In the Epic-kitchens annotation files, I could only find 'EPIC_video_info.csv' and not 'EPIC_video_info_dict.pkl' required at 'https://github.com/noureldien/videograph/blob/master/datasets/epic_kitchens.py#L90. Is the file present somewhere else or we need to convert from csv to pkl? 
2) The function signature you use 'Inception_Inflated3d_Backbone' at https://github.com/noureldien/videograph/blob/master/datasets/epic_kInceptionInception_Inflated3d_Backbone_Inflated3d_Backboneitchens.py#L709 is different from 'Inception_Inflated3d' at https://github.com/dlpbc/keras-kinetics-i3d/releases. Just wanted to double check if it's the same file or not.
3) So if I understand correctly, for pre-processing the Epic-kitchens datasets, we need to run all the functions in the 'epic_kitchens' python file (in order), right?
4) Any plans on releasing pre-processing scripts for the other datasets? 

Thanks!

**Comment by noureldien** [comment]
Thanks for asking
1. If you notice, we only use EPIC_video_info_dict to get the video frames_per_second. But in any case, I've added it to github
2. It is the same as /keras-kinetics-i3d, no changes. In any case, I uploaded the file.
3. Your starting point is main.py and `epic_kitchens.train_model_videograph()`, also, could you please read these notes carefully? This provided code is meant as an example only, not meant to reproduce the results in the paper.  https://github.com/noureldien/videograph/blob/master/experiments/epic_kitchens.py#L92
4. For other datasets, we follow steps used in Epic-Kitchens

**Comment by noureldien** [comment]
Please, let me know if you've any more questions. I hope I've answered yours.

**Comment by na-hri** [comment]
Hi,

I understand. I do have a few more questions and would really appreciate if you could answer them:

1. In the [comments](https://github.com/noureldien/videograph/blob/8a419efa74a72b93472a2461f12b5a35ca6a2fef/experiments/epic_kitchens.py#L92) you mention about random sampling of frames every epoch for better performance. Is that something you do in the paper as well?
2. Can the current version of the code be used to reproduce the results in your paper? If not, can you please list out the exact steps required to do so.

Thanks!

**Comment by na-hri** [comment]
@noureldien Just a reminder. Would really appreciate your response on the above issue.

**Comment by noureldien** [comment]
Hi Nakul,
Thanks for asking. Please, expect code updates on GitHub by this Friday. The updates will answer your questions.

**Comment by noureldien** [comment]
Hello Nakul,
I've updated the codes for Epic-Kitchens, and Breakfast
