### ISSUE TITLE
Your underlying idea behind node attention module

### ISSUE THREAD

**Issue by sudonto** [noureldien/videograph#3]
Hi, nice work and thanks for sharing this work publicly. Anyhow, I would like to ask something that confuse me.

Could you tell me your motivation behind "node attention" module. I have ran your code successfully and I examined your code and read your papaer fully. I cannot understand the correlation between "generating number randomly for latent features", "unit-actions describing a group sequence of activity", and "temporal order of unit actions". I cannot find this correlation or your motivation or your underlying idea in your paper (chapter "Method").

- What makes you think that to emphasize/reveal unit actions in a video, a random number (in this case 128) can be used to capture the key unit-action after several epochs? Although your result of experiments show prominent results but I just cannot understand this correlation **logically**.
- Why you choose number of 128 as latent feature?
- If I don't want to reveal the connection between each unit action in graph, can I skip the graph embedding node and connect the output of node attention module to classifier directly? Thus, no temporal relationship modelling.
- You mentioned that this network is suitable for minutes-long video, but I wonder if this net can also be applied for very short video, 3-sec video for example?

**Comment by noureldien** [comment]
Hi, thanks for your question.
Please, can you send me your skype or google hangouts to reply to your questions? My e-mail is nhussein @ uva.nl

**Comment by noureldien** [comment]
To answer your questions.
1. I'm not saying to learn unit actions, random vectors will do. I'm saying, using a K randomly initialize random vectors, you can learn K latent concepts from a video dataset. A latent concept can be object-centric as (food box, pan, knife, egg, ...) or action-centric (slice, cut, wash, open).
In our paper, these latent concepts are learned by a dense layer in the node embedding block. The nodes in our paper are analogous to the learned centroids in ActionVLAD.
2. K=128 is cross-validated.
3. So, if you feed the video features X \in R^{C x H x W x T} to our model. The output of node-embedding will be Y \in R^{C x H x W x T x N}. Assume you average / maxpool over space/time, which is a huge compromise, you get Y \in R^{C x N}. Then, how do you classify Y using MLP? Maybe you flatten in to Y \in R^{C*N x 1}? Then, it's not much of a difference then from NetVLAD. The purpose of the graph-embedding block is not only learning node-wise and time-wise correlations, but also to reduce the feature space into a sizable vector to be classified.
4. I guess it the 3-sec video heavily depends on motion and arrow-of-time, as in 20BN-Something-Something dataset, you're better off using standard 3D CNNs.

**Comment by sudonto** [comment]
Hi @noureldien , thanks for your reply, I will try to catch your explanation.
